---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: php-golden-image
spec:
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: "https://github.com/golden-image-example/php"
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: main
  - name: php-containerfile-location
    type: string
    default: "/8.2-fpm/Containerfile"
  - name: php-image-name
    type: string
    default: "image-registry.openshift-image-registry.svc:5000/golden-image-example/php:8.2-fqm"
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-and-push-php-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.php-image-name)
    - name: DOCKERFILE
      value: $(params.php-containerfile-location)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  workspaces:
    - name: shared-workspace